# Sofia Billger Bergström - Kunskapskontroll 1.1 - NumPy

# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [7]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [8]:
A = np.arange(1, 16).reshape(3, 5)

In [66]:
import numpy as np


def arrange(start, stop, step, shape):  # Function to create a matrix with a given shape
    A = np.arange(start, stop, step)
    A = A.reshape(shape)
    return A


A = np.arange(1, 16).reshape(3, 5)  # 1-15 inclusive in 3x5 matrix form
type(A)
print(A, type(A))
print(arrange(1, 16, 1, (3, 5)))
print(arrange(1, 16, 1, (3, 5)).dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
int64


the code above creates a 3x5 matrix with values from 1 to 15. The type of the matrix is numpy.ndarray. // Sofia

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [10]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [11]:
import numpy as np


# Function to create a matrix with a given shape
def arrange(start, stop, step, shape):
    A = np.arange(start, stop, step)
    A = A.reshape(shape)
    return A


# Create the matrices B and C
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

subtract = B - C  # Elementwise subtraction
print(subtract)

multiply = B * C  # Elementwise multiplication
print(multiply)

matrix_multiply = B @ C  # Matrix multiplication
print(matrix_multiply)


[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


after defining the matrices B and C, the code above calculates the elementwise subtraction, elementwise multiplication and matrix multiplication for the matrices. // Sofia

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculate the minimum value in each row. 
* Calculate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [28]:
## B = np.arange(1, 10).reshape(3, 3)
## print(B)

In [30]:
import numpy as np


# Function to create a matrix with a given shape
def arrange(start, stop, step, shape):
    B = np.arange(start, stop, step)
    B = B.reshape(shape)
    return B


B = np.arange(1, 10).reshape(3, 3)  # Create a 3x3 matrix with values from 1 to 9
print(B)

np.set_printoptions(
    formatter={"int": lambda x: "{0:3d}".format(x)})  # set print options to print integers with 3 digits

# Calculate accordingly to the instructions above and print the result 
print(np.exp(B), np.min(B), np.min(B, axis=0),
      np.min(B, axis=1), np.argmin(B), np.argmin(B, axis=0),
      np.argmin(B, axis=1), np.sum(B), np.mean(B, axis=0),
      np.mean(B, axis=1), np.median(B, axis=1))




[[  1   2   3]
 [  4   5   6]
 [  7   8   9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 1 [  1   2   3] [  1   4   7] 0 [  0   0   0] [  0   0   0] 45 [4. 5. 6.] [2. 5. 8.] [2. 5. 8.]


The definition and method calls above creates a 3x3 matrix with values from 1 to 9 and calculates the exponentiation, minimum value in the whole matrix, minimum value in each row, minimum value in each column, index value for the minimum value in the whole matrix, index value for the minimum value in each row, sum for all elements, mean for each column and median for each column. // Sofia

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [14]:
print(A)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [15]:
A[1]

array([  6,   7,   8,   9,  10])

**Answer:** When you provide fewer indices than axes when slicing, it will return the entire row for the given column index. Therefore, in the example above it will return the second row since the index is 1. In this case, a 1D array. // Sofia

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate through the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [16]:
A

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15]])

In [17]:
for i in A:
    print(i)

[  1   2   3   4   5]
[  6   7   8   9  10]
[ 11  12  13  14  15]


**Answer:** To iterate through the array elementwise, you can use the flat attribute, as I use in the code below. // Sofia

In [18]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [19]:
a = np.arange(30)  # Create an array with values from 0 to 29
b = a.reshape((2, 3, -1))  # Reshape the array into a 3D array
print(a)  # Print the array
print()  # Print a blank line

print(b)  # Print the 3D array

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]

[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]]

 [[ 15  16  17  18  19]
  [ 20  21  22  23  24]
  [ 25  26  27  28  29]]]


Answer:  Since the B arrays has three axes, the code reshapes the array into a 3D array. -1 is used to automatically calculate the size of the third axis. Using print() between the two point statements a blank line will separate them. // Sofia

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [20]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[  2   3]
 [  4   5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [21]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[  2   3   4]


In [22]:
A = np.arange(1, 5).reshape(2, 2)
print(A)

b = np.array([2, 2])
print(b)

[[  1   2]
 [  3   4]]
[  2   2]


mathematical rules in Linear Algebra would not allow the operation below. However, it works due to broadcasting in NumPy.

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [65]:


def validate_input(matrix1, matrix2, add_or_multiply):
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):  # Validate input
        return "Input must be numpy.ndarray"
    if add_or_multiply is not None and not isinstance(add_or_multiply, str):  # Validate input
        return "Third argument must be a string"
    if add_or_multiply not in ['add', 'multiply']:  # Validate input
        return "Third argument must be 'add' or 'multiply'"
    return None


def validate_size(matrix1, matrix2, add_or_multiply):
    if add_or_multiply == 'add':  # Add matrices
        if matrix1.shape != matrix2.shape:  # Validate size
            return "Matrices must have the same size"
    elif add_or_multiply == 'multiply':  # Multiply matrices
        if matrix1.shape[1] != matrix2.shape[1]:  # Validate size
            return "Number of columns in matrix1 must be equal to number of columns in matrix2"
    return None


def get_matrix_input(promt):  # Define the function matrix_input():
    matrix = []
    while True:
        row = input(promt)
        if not row:
            break
        row_values = row.split(', ')
        matrix.append(list(map(float, row_values)))
    return np.array(matrix)


def add_mult_matrices(matrix1, matrix2, add_or_multiply):
    validation_result = validate_input(matrix1, matrix2, add_or_multiply)
    if validation_result is not None:
        return validation_result
    validation_result = validate_size(matrix1, matrix2, add_or_multiply)
    if validation_result is not None:
        return validation_result
    if add_or_multiply == 'add':  # Add matrices
        return matrix1 + matrix2
    elif add_or_multiply == 'multiply':  # Multiply matrices
        return matrix1 @ matrix2


def get_user_input():
    while True:
        matrix1 = get_matrix_input("Enter matrix 1 (space-separated values, rows separated by newline): ")
        matrix2 = get_matrix_input("Enter matrix 2 (space-separated values, rows separated by newline): ")
        print("Enter 'add' or 'multiply' to add or multiply matrices")
        add_or_multiply = input()
        if add_or_multiply in ['add', 'multiply']:
            return matrix1, matrix2, add_or_multiply
        else:
            print("Invalid input. Must be 'add' or 'multiply'")


def main():
    while True:
        matrix1, matrix2, _ = get_user_input()  # Call the function get_user_input()

I have created functions to validate the input and sizes of the matrices, as well as functions to get the input from the user and to add or multiply the matrices. I have not yet implemented the main function to run the program. // Sofia

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

#10.1.2. Definiera vektorn v enligt v = (3 7 0 11)

#10.1.2a) Vilken dimension har vektorn v?

#10.1.2b) Beräkna 2v

#10.1.2c) Beräkna 5v + 2v

#10.1.2d) Beräkna 4v - 2v

#10.1.2e) Beräkna v T (transponatet av v), vilken blir den nya dimensionen?

#10.1.2f) Beräkna ||v||

In [ ]:
import numpy as np

v = np.array([3, 7, 0, 11])  # Define the vector v
print(v)

#10.1.2a) The dimension of the vector v
print(
    v.ndim)  # the v.ndim attribute returns the number of axes (dimensions) of the array. In this case, the vector v has 1 axis and therefore is a 1D array

#10.1.2b) Calculate 2v
print(2 * v)  # Multiply each element in the vector v by 2

#10.1.2c) Calculate 5v + 2v
print(5 * v + 2 * v)  # Multiply each element in the vector v by 5 and 2 respectively and add the results

#10.1.2d) Calculate 4v - 2v
print(4 * v - 2 * v)  # Multiply each element in the vector v by 4 and 2 respectively and subtract the results

#10.1.2e) Calculate v T (the transpose of v), which is the new dimension?
print(
    v.T)  # The transpose of the vector v is obtained by swapping the rows and columns of the matrix representation of the vector. In this case, the new dimension is 4x1, meaning the vector v is a 4D array

#10.1.2f) Calculate ||v||
print(np.linalg.norm(
    v))  # The norm of the vector v is calculated using the np.linalg.norm() function. Meaning the v norm is the square root of the sum of the squares of the elements in the vector v

#10.1.3. Definera vektorerna v1 = (4, 3, 1, 5) och v2 = (2, 3, 1, 1)

#10.1.3a) Beräkna ||v1||

#10.1.3b) Beräkna ||v1 -v2||

In [ ]:
import numpy as np

v1 = np.array([4, 3, 1, 5])  # Define the vector v1
v2 = np.array([2, 3, 1, 1])  # Define the vector v2
print(v1)
print(v2)

#10.1.3a) Calculate ||v1||
print(np.linalg.norm(
    v1))  # The norm of the vector v1 is calculated using the np.linalg.norm() function. Meaning the v1 norm is the square root of the sum of the squares of the elements in the vector v1. This will give the length of the vector v1.

#10.1.3b) Calculate ||v1 -v2||
print(np.linalg.norm(
    v1 - v2))  # The norm of the difference between the vectors v1 and v2 is calculated using the np.linalg.norm() function. Meaning the norm of the difference is the square root of the sum of the squares of the elements in the vector v1 - v2

#10.1.1 Definera vektorn x enligt x = (4,3)

#10.1.1a) Vilken dimension har vektorn x?

#10.1.1b) Beräkna 5x

#10.1.1c) Beräkna 3x

#10.1.1d) Beräkna 5x + 3x

#10.1.1e) Beräkna 8x

#10.1.1f) Beräkna 4x - x

#10.1.1g) Beräkna x T (transponatet av x), vilken blir den nya dimensionen?

#10.1.1h) Är x + x T definierat?

#10.1.1i) Beräkna ||x|| 

In [ ]:
import numpy as np

x = np.array([4, 3])  # Define the vector x
print(x)

#10.1.1a) The dimension of the vector x
print(
    x.ndim)  # the x.ndim attribute returns the number of axes (dimensions) of the array. In this case, the vector x has 1 axis and therefore is a 1D array

#10.1.1b) Calculate 5x
print(5 * x)  # Multiply each element in the vector x by 5

#10.1.1c) Calculate 3x
print(3 * x)  # Multiply each element in the vector x by 3

#10.1.1d) Calculate 5x + 3x
print(5 * x + 3 * x)  # Multiply each element in the vector x by 5 and 3 respectively and add the results

#10.1.1e) Calculate 8x
print(8 * x)  # Multiply each element in the vector x by 8

#10.1.1f) Calculate 4x - x
print(4 * x - x)  # Multiply each element in the vector x by 4 and subtract the results

#10.1.1g) Calculate x T (the transpose of x), which is the new dimension?
print(
    x.T)  # The transpose of the vector x is obtained by swapping the rows and columns of the matrix representation of the vector. In this case, the new dimension is 2x1, meaning the vector x is a 2D array

#10.1.1h) Is x + x T defined?
print(np.array_equal(x + x.T,
                     x.T + x))  # The addition of the vector x and its transpose is equal to the addition of the vector x and its transpose. Therefore, the addition is defined. 

#10.1.1i) Calculate ||x||
print(np.linalg.norm(
    x))  # The norm of the vector x is calculated using the np.linalg.norm() function. Meaning the x norm is the square root of the sum of the squares of the elements in the vector x. This will give the length of the vector x.

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan".

#10.2.1. Definiera matriserna:

A = [2 1 -1]
    [1 -1 1]

B = [4 -2 1]
    [2 -4 -2]

C = [1 2]
    [2 1]

D = [3 4]
    [4 3]

E = [1 2]

I = [1 0]
    [0 1]

Om det är definerat, utför följande beräkningar:

#10.2.1a) 2A

#10.2.1b) B - 2A

#10.2.1c) 3C - 2E

#10.2.1d) 2D - 3C

#10.2.1e) D T (transponatet av D) + 2D

#10.2.1f) 2C T (transponatet av C) - 2D T (transponatet av D)

#10.2.1g) A T (transponatet av A) - B

#10.2.1h) AC

#10.2.1i) CD

#10.2.1j) CB

#10.2.1k) CI

#10.2.1l) AB T (transponatet av B)

In [ ]:
import numpy as np

#10.2.1. Define the matrices:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1, 2]])
I = np.array([[1, 0], [0, 1]])
print(A)
print(B)
print(C)
print(D)
print(E)
print(I)

#10.2.1a) Calculate 2A
print(2 * A)  # Multiply each element in the matrix A by 2

#10.2.1b) Calculate B - 2A
print(
    B - 2 * A)  # Subtract the second matrix A from the first matrix B by multiplying each element in the second matrix A by 2 and subtracting the result from the first matrix B

#10.2.1c) Calculate 3C - 2E
print(
    3 * C - 2 * E)  # Subtract the second matrix E from the first matrix C by multiplying each element in the second matrix E by 2 and subtracting the result from the first matrix C

#10.2.1d) Calculate 2D - 3C
print(
    2 * D - 3 * C)  # Subtract the second matrix C from the first matrix D by multiplying each element in the second matrix C by 3 and subtracting the result from the first matrix D

#10.2.1e) Calculate D T + 2D (the transpose of D), which dimension is the new one?
print(
    D.T + 2 * D)  # The transpose of the matrix D is obtained by swapping the rows and columns of the matrix representation of the matrix. In this case, the new dimension is 2x2, meaning the matrix D is 2D array

#10.2.1f) Calculate 2C T - 2D T
print(
    2 * C.T - 2 * D.T)  # Subtract the second matrix D.T from the first matrix C.T by multiplying each element in the second matrix D.T by 2 and subtracting the result from the first matrix, C.T. The new dimension is 2x2, meaning the matrix C is 2D array

#10.2.1g) Calculate A T - B
print(
    A.T - B)  # Subtract the second matrix B from the first matrix A.T by subtracting the result from the first matrix, A.T. The new dimension is 2x2, meaning the matrix A is 2D array

#10.2.1h) Calculate AC
print(
    A @ C)  # Multiply the matrix A by the matrix C using the @ operator. The new dimension is 2x2, meaning the matrix C is 2D array

#10.2.1i) Calculate CD
print(
    C @ D)  # Multiply the matrix C by the matrix D using the @ operator. The new dimension is 2x2, meaning the matrix D is 2D array

#10.2.1j) Calculate CB
print(
    C @ B)  # Multiply the matrix C by the matrix B using the @ operator. The new dimension is 2x2, meaning the matrix B is 2D array

#10.2.1k) Calculate CI
print(
    C @ I)  # Multiply the matrix C by the matrix I'm using the @ operator. The new dimension is 2x2, meaning the matrix I is 2D array

#10.2.1l) Calculate AB T (the transpose of B)
print(
    A @ B.T)  # Multiply the matrix A by the matrix B.T using the @ operator. The transpose of the matrix B is obtained by swapping the rows and columns of the matrix representation of the matrix. In this case, the new dimension is 2x2, meaning the matrix B is 2D array

#10.2.2. Definiera matrisen:

A = [2 3 4]
    [5 4 1]

Beräkna: AA T (transponatet av A)

In [ ]:
import numpy as np

A = np.array([[2, 3, 4], [5, 4, 1]])  # Define the matrix A
print(A)  # Print the matrix A
print(
    A.T)  # Print the transpose of the matrix A. The transpose of the matrix A is obtained by swapping the rows and columns of the matrix representation of the matrix. In this case, the new dimension is 3x2, meaning the matrix A is a 3D array

#10.2.3. Definiera matriserna:

A = [1 2]
    [2 4]

B = [2 1]
    [1 3]

C = [4 3]
    [0 2]

Verifiera att AB = AC men att B ≠ C

Vad vill vi demonstrera med detta exempel är att vi har definerat ett nytt matematiskt objekt, matriser i detta fallet, som inte följer de vanliga reglerna för multiplikation. Vi kan multiplicera matriser med varandra.

In [ ]:
import numpy as np

A = np.array([[1, 2], [2, 4]])  # Define the matrix A
B = np.array([[2, 1], [1, 3]])  # Define the matrix B
C = np.array([[4, 3], [0, 2]])  # Define the matrix C
print(
    A @ B == C)  # Verify that the matrix A multiplied by the matrix B is equal to the matrix C. The @ operator is used to multiply the matrices. The result is True, meaning AB = AC
print(B == C)  # Verify that the matrix B is not equal to the matrix C. The result is False, meaning B ≠ C

#10.2.4. Skriv det linja ekvationssystemet nedan på formen Ax = b

3x nedsänkt 1 + 2x nedsänkt 2 + 4x nedsänkt 3 = 7

2x nedsänkt 1 + 3x nedsänkt 2 + 7x nedsänkt 3 = 4

4x nedsänkt 1 + x nedsänkt 2 + 3x nedsänkt 3 = 11

7x nedsänkt 1 + x nedsänkt 2 + 5x nedsänkt 3 = 9

Verifiera att lösningen till ekvationssystemet genom att skriva ut matrismultiplikationen Ax = b och jämför med det urspringliga ekvationssystemet.

In [ ]:
import numpy as np

A = np.array([[3, 2, 4], [2, 3, 7], [4, 0, 3], [7, 2, 5]])  # Define the matrix A
b = np.array([7, 4, 11, 9])  # Define the vector b
print(
    A @ b)  # Print the matrix A multiplied by the vector b using the @ operator. The result is the solution to the equation system. The new dimension is 4x1, meaning the vector b is a 4D array, and the matrix A is a 4D array

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [1]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

NameError: name 'np' is not defined

In [25]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2   3]


In [26]:
# The last element in v1 will be changed as well since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
