# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

imported numpy to solve the exercises

```python

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:
A = np.arange(1, 16).reshape(3,5)

In [11]:
import numpy as np

def arrange (start, stop, step, shape):
    A = np.arange(start, stop, step)
    A = A.reshape(shape)
    return A
A = np.arange(1, 16).reshape(3,5) # 1-15 inclusive in 3x5 matrix form
type(A)
print(A, type(A))
print(arrange(1, 16, 1, (3,5)))
print(arrange(1, 16, 1, (3,5)).dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] <class 'numpy.ndarray'>


to start the exercise, I imported nympy to my code cell.



### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

In [16]:
import numpy as np

def arrange(start, stop, step, shape):
    A = np.arange(start, stop, step)
    A = A.reshape(shape)
    return A

B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

subtract = B - C
print(subtract)

multiply = B * C
print(multiply)

matrix_multiply = np.dot(B, C)
print(matrix_multiply)


[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


to be able to solve this exercise I imported the numpy library to my code cell and created two matrices B and C. I then performed the operations requested in the exercise on the matrices B and C.

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

In [ ]:
import numpy as np

def arange(start, stop, step, shape):
    B = np.arange(start, stop, step)
    B = A.reshape(shape)
    return B

B = np.arange(1, 10).reshape(3, 3)
print(B)



np.exp(B) # exponentiate all elements of B
np.min(B) # find the minimum value of B
np.calculate.min(B)  # calculate the minimum value of the column i B
np.calculate.min(B, axis=1) # calculate the minimum value of each row in B
np.argmin(B) # fin the index value for the minumen value in the whole matrix
np.argmin(B, axis=0) # find the index value for the minimum value in each row
np.calculate.sum(B) # calculate the sum of all elements in B
np.calculate.mean(B, axsis=0) # calculate the mean of each row in B
np.calculate.mean(B, axsis=1) # calculate the mean of each column in B
np.calcuate.median(B, axsis=1) # calculate the median of each column in B

print(np.exp(B))
print(np.min(B))
print(np.min(B, axis=0))
print(np.argmin(B))
print(np.argmin(B, axis=0))
print(np.sum(B))
print(np.mean(B, axis=0))
print(np.mean(B, axis=1))
print(np.median(B, axis=1))

def calculate(B):
    return np.exp(B), np.min(B), np.min(B, axis=0), np.argmin(B), np.argmin(B, axis=0), np.sum(B), np.mean(B, axis=0), np.mean(B, axis=1), np.median(B, axis=1)




for this exercis I have first imported the numpy libary to create a matrix. after that I have defined the function that will perform the operations. The following operations were performed on the matrix: exponentiate each number elementwise, calculate the minimum value in the whole matrix, calculate the minimum value in each row, calculate the minimum value in each column, find the index value for the minimum value in the whole matrix, find the index value for the minimum value in each row, calculate the sum for all elements, calculate the mean for each column, and calculate the median for each column.


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

Answer: 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

to be able to solve this exercise I imported the numpy library to my code cell and created two matrices m1 and m2. I then performed the operations requested in the exercise on the matrices m1 and m2.

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

mathematical rules in Linear Algebra would not allow the operation below. However, it works due to broadcasting in NumPy.

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

to solve this exercise I created a function called add_mult_matrices that takes two matrices as input arguments, a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices. I then validated that the input are of the type numpy.ndarray by using the isinstance function. I also validated that the third argument is either 'add' or 'multiply'. When doing matrix addition, I validated that the matrices have the same size. When doing matrix multiplication, I validated that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

```python

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

to solve this exercise I read chapter 10.1 in the book "Matematik för yrkeshögskolan" and solved all the exercises in the chapter.

```python

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

in this exercise, I read chapter 10.2 in the book "Matematik för yrkeshögskolan" and solved all the exercises in the chapter except 10.2.4.

```python

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

to answer this question I created two arrays v1 and v2. I then checked if v1 and v2 is a view or copy. I then changed the last element in v2 to 123 and checked if the last element in v1 was changed. I then explained why the last element in v1 was not changed.

```python

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

this mean that the last element in v1 was not changed because v1 and v2 are views of the same array.

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

to solve this exercise I created two arrays v1 and v2. I then checked if v1 and v2 is a view or copy. I then changed the last element in v2 to 123 and checked if the last element in v1 was changed. I then explained why the last element in v1 was not changed.

```python